USE LAB6
GO
ALTER TABLE COURS_MACHINE
  ADD FOREIGN KEY (cours)
REFERENCES COURS (id)
GO
ALTER TABLE COURS_MACHINE
  ADD FOREIGN KEY (machine)
REFERENCES MACHINE (id)
GO
ALTER TABLE SALLE
  ADD FOREIGN KEY (machine)
REFERENCES MACHINE (id)
GO
ALTER TABLE FORMATION
  ADD FOREIGN KEY (cours)
REFERENCES COURS (id)
GO
ALTER TABLE FORMATION
  ADD FOREIGN KEY (salle)
REFERENCES SALLE (id)
GO


